# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        image-version: latest
        port: 27017
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Checkout Collar
      uses: actions/checkout@master
      with:
        repository: team-catgirl/collar
        path: collar
    - name: Build collar API
      run: mvn clean install
      working-directory: collar
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout mod
      uses: actions/checkout@v2
      with:
        path: mod
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: mod
    - name: Setup workspace
      run: ./gradlew setupDecompWorkspace
      working-directory: mod
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: mod
    - name: Upload collar-client.jar
      uses: actions/upload-artifact@v2
      with:
        name: collar-client.jar
        path: mod/build/build/libs/team.catgirl.collar*.jar
